---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
spec:
  interval: 5m
  url: https://charts.longhorn.io

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5s
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: longhorn
      chart: longhorn
      version: 1.10.0
  values:
    persistence:
      defaultClassReplicaCount: 2
      reclaimPolicy: Retain

    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1

    longhornUI:
      replicas: 1

    defaultSettings:
      allowCollectingLonghornUsageMetrics: false
      defaultReplicaCount: "2"
      deletingConfirmationFlag: true
      storageMinimalAvailablePercentage: "10"
