apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
spec:
  interval: 24h
  url: oci://ghcr.io/traefik/helm/traefik
  ref:
    tag: 37.1.1
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
sops:
  age:
    - recipient: age1mz6mvlp9fu44qpr29lrpuw57y9akt8upx7w43zdz83kgatnufu7q7mvtvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MGMycm1VK2VlTjAyTWJw
        VzlCeFJ5UFRlNW9SM1RWM0h5UzFPNVJjVlVFCjMzcTFjYTJLbVhkelRERmt3UnZN
        RXRBaHJ4U0NxdkxTenJuTjllNXBrbkEKLS0tIDZXSkJxbzJDL2U2UDQ0a1ZnSUJO
        cWZWZVJXdFFkcW5UdFV4Rm1QS3ptemcKpGP2pr41hauezq+/IcOQZielkKT8jhXP
        qcA2K/27NapFIcWk0qmZX+Kp5I64Vv6xsGm3j7lOIe47yGSxRSZr9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T23:34:49Z"
  mac: ENC[AES256_GCM,data:EklIb40Rcx3V11unlSlU9yAEYkV5+CVLIq4Jv1pZJR+POnn3HmHZrFGwb2WKwX5YjD+IGOK1MHeBrWAa1W7gjMOIhL5bLAkq1szsqCTY37SBBstMd9f19W51YQg7VE9r3So3T9cy4mqb5XlwqKMIjsBIIxyRka0dW4qaVVy0dsA=,iv:lFonTsK7PBsSrygEzC/dB84Os5Dn0YsE1I7fi79W8Ho=,tag:oqutp3mD8B1EeUvqbiyYyg==,type:str]
  encrypted_regex: ^(data|hostname|hostnames)$
  version: 3.10.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5s
  chartRef:
    kind: OCIRepository
    name: traefik
  values:
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    deployment:
      replicas: 1
    ingressRoute:
      dashboard:
        enabled: true
    providers:
      kubernetesGateway:
        enabled: true
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        http3:
          enabled: false
    logs:
      access:
        enabled: true
    gateway:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      listeners:
        web:
          hostname: ENC[AES256_GCM,data:le92wArZiSw=,iv:JOPs66C42LnLPkQVgSck8HsiW/fjNYRDxsVY1jNN+O0=,tag:TX8heXzTfTBIY7Qp6q7uhA==,type:str]
          namespacePolicy:
            from: All
        websecure:
          port: 8443
          protocol: HTTPS
          hostname: ENC[AES256_GCM,data:/WM7Hk/2+Pk=,iv:8Ng0TgUgXe8wBCD5ua6HNdIHWXec/r2oUsevrRYsDTQ=,tag:nJUDrBx/1EgpkwHt6At9NA==,type:str]
          namespacePolicy:
            from: All
          certificateRefs:
            - name: traefik-tls
          mode: Terminate
    service:
      annotations:
        oci.oraclecloud.com/load-balancer-type: nlb
        service.beta.kubernetes.io/oci-load-balancer-internal: "false"
sops:
  age:
    - recipient: age1mz6mvlp9fu44qpr29lrpuw57y9akt8upx7w43zdz83kgatnufu7q7mvtvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MGMycm1VK2VlTjAyTWJw
        VzlCeFJ5UFRlNW9SM1RWM0h5UzFPNVJjVlVFCjMzcTFjYTJLbVhkelRERmt3UnZN
        RXRBaHJ4U0NxdkxTenJuTjllNXBrbkEKLS0tIDZXSkJxbzJDL2U2UDQ0a1ZnSUJO
        cWZWZVJXdFFkcW5UdFV4Rm1QS3ptemcKpGP2pr41hauezq+/IcOQZielkKT8jhXP
        qcA2K/27NapFIcWk0qmZX+Kp5I64Vv6xsGm3j7lOIe47yGSxRSZr9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T23:34:49Z"
  mac: ENC[AES256_GCM,data:EklIb40Rcx3V11unlSlU9yAEYkV5+CVLIq4Jv1pZJR+POnn3HmHZrFGwb2WKwX5YjD+IGOK1MHeBrWAa1W7gjMOIhL5bLAkq1szsqCTY37SBBstMd9f19W51YQg7VE9r3So3T9cy4mqb5XlwqKMIjsBIIxyRka0dW4qaVVy0dsA=,iv:lFonTsK7PBsSrygEzC/dB84Os5Dn0YsE1I7fi79W8Ho=,tag:oqutp3mD8B1EeUvqbiyYyg==,type:str]
  encrypted_regex: ^(data|hostname|hostnames)$
  version: 3.10.2
