---
# requires flux-operator
#
# https://fluxcd.control-plane.io/operator/flux-config/
# https://fluxcd.control-plane.io/operator/fluxinstance/

apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
spec:
  distribution:
    version: "2.6.x"
    registry: "ghcr.io/fluxcd"

  components:
    - source-controller
    - helm-controller
    - kustomize-controller

  cluster:
    type: kubernetes
