---

# 1. Install manually using helm:
#
#   $ helm upgrade \
#     --install \
#     --namespace flux-system \
#     --create-namespace \
#     --wait \
#     flux-operator \
#     oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
#
# 2. Apply this file, so flux takes over the helm release

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - flux-operator.yaml
  - flux-instance.yaml
