---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kener
generators:
  - secret-generator.yaml
resources:
  - namespace.yaml
  - helm-cnpg.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - service.yaml
