apiVersion: v1
kind: Secret
metadata:
  name: kener
type: Opaque
data:
  KENER_SECRET_KEY: ENC[AES256_GCM,data:RRN7rebOTcEhuGvztRk+KcDa+HR+vazZAd2FhpfjDI+/h5PBGidqWSki+FOWHNrBP2ojaw==,iv:oEaldq9xto+FamuU+tnlZPXQk0q/oIZ+r9mEqUVj8p0=,tag:oKZrndkL9H1hzUbutIWjRQ==,type:str]
  ORIGIN: ENC[AES256_GCM,data:SIafoOY2Q+fo5V3RrvHneoufUrSEC2E5AiakV9Jx0DI=,iv:cafclsd9dMP31g5i5y6caTXDZHOpmHEI0nGXxNFQeoU=,tag:YWA1HMLzfzAlJOMrJ0oHTA==,type:str]
  RESEND_API_KEY: ENC[AES256_GCM,data:6+I1cJk8rjiOmDJ4nJc+j2v3Q14AyxitAyuNJ2jaqaNgLDyBZReVrY5XGTpTedaJLQdYXQ==,iv:sOT/yTM4iFMmLWtVs79ND30yZ9DnkW7Qmg0HjKYvVcI=,tag:btxivg5AJdUtyZvm7HtgSg==,type:str]
  RESEND_SENDER_EMAIL: ENC[AES256_GCM,data:LOiMKgLubZvC2sDymvmSgoFjQvMvbx9TQYEMGhj52SkPjCwSJZkeUatOoeRqvy6cQ/xDPrEv6jpBid0UqUCq/JaenQ0Yg6OFfvQMrQ==,iv:T8UAuuAIrScogseIqSAFLLp630gYEpIFnHNH4wApbvE=,tag:gHo7WqMHRbKBfOKKMPFSGg==,type:str]
sops:
  age:
    - recipient: age1mz6mvlp9fu44qpr29lrpuw57y9akt8upx7w43zdz83kgatnufu7q7mvtvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVVNuRzZaemtZMmZTSW1R
        UEI1cytxYTUwR3hRbFRJYmw4WTc0cWdRVGwwCmRqMU5pL2o4b1ZyUFhWamZKY25x
        L0puWjQrRGxOOFd6K0FZaXU2S0dUZlUKLS0tIG81TEFWR3hFNGtIT2Z0azFTd2Nx
        RU1qUXZhenY3QmR1SXdTekYvOFk2QTAKKr1773cXa5NtQ809W7i43ZAX1I5XWEMM
        vyckUR/qcSPhNiiDyzap+0scBiwHxwjw0sO4Q2kU40fInJDS2yFqqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T03:59:17Z"
  mac: ENC[AES256_GCM,data:P7xge8dFQ9eQpEc+posSkzz3aa54iYLOH74O6cNDRmMF5Cd/YhSCuiJ69SCySup9V0b+liEb7zhZw1FWoeZ1VeSPJZ3V8Dkw21DjfEtCmZJl5wxh0ZX5KeApri3MbO6r6fPgC0GdPltEs/r6Q8+W/ZHyCri0KQ9cT5DaX/gBnT4=,iv:o1VEEOcpHlDCsZ1YRcPIcGTusZdmTplQh1W/bttvKoo=,tag:FT2nD/ntWcbqvMAr9iofmA==,type:str]
  encrypted_regex: ^(data|hostname|hostnames|host)$
  version: 3.11.0
