---

apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-cloudflare-token
type: Opaque
data:
  apiToken: ENC[AES256_GCM,data:jbQMtJzsl0H+mTtD+fFvYHvppn5I0QFyiSQqbmPDgWECwRoI8T8eNoqU9IxyuZ7EwB70/Rl48Sk=,iv:FVdDMIpi4a+8I6IIgnwbkUHLYB+Gp+ZH70kwLu6MVcU=,tag:BWC12irGO3zuVfhKUeNHRw==,type:str]
sops:
  age:
    - recipient: age1mz6mvlp9fu44qpr29lrpuw57y9akt8upx7w43zdz83kgatnufu7q7mvtvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2M1BHc3dEaW1WQnR1dVQ5
        TjVDV1Q4bGNWRm92b05oMUFGa0M3YUFSVERVCmxtV0IzODAzdmFKNlFtNG1zVVkx
        WllBWS9rWFMzam1wa3JlSXVBTU4vQVEKLS0tIHNyblFtZnBIL2ljcGNMM3M2cC9Y
        NjcyU3VtUmFGRnl1NWtvWkIwMmJpMWMKlqCm0GPTVeqnkZ28zmUzF58iEVMrWECw
        UOI/t0NNpO9G9HwuXynt/b2fjmTeA/dTlyLEGZi7NEZ5jRbEYMyUsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-26T09:52:22Z"
  mac: ENC[AES256_GCM,data:Q76lczr/TsjM137TRwvCqYUZwRG8dG7lhieCgoUO0ez3d4QTVEiT/Te52s1Q94ep/FG1MR8QL2/lcenpJ6+3YckXsnGpLDIbbiX58ZxyZjBHg6CQ7f/fm+cKEKAvv9cV1e0bQROC7PRBEvYDY/MK9MM+vEliFmAJ/pwbX4U3irE=,iv:hjSncvBg4BhAT5tBHByNW7rlAYYxQ1qsHjxNXl8frQc=,tag:Po4057IZpECFojUteImfqA==,type:str]
  encrypted_regex: ^(data|hostname)$
  version: 3.10.2
